### ISSUE TITLE
部署报错

### ISSUE THREAD

**Issue by bernylinville** [X3ZvaWQ/gubot#11]
```
/home/ubuntu/gubot/src/service/bot.js:208
            let [args, command] = await this.parseArgs(data) ?? [];
                                                              ^


SyntaxError: Unexpected token ?
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/ubuntu/gubot/app.js:3:13)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
```

尝试删掉，再报错
```
[2021-07-09 14:43:09][SUCCESS] Redis: init successed
[2021-07-09 14:43:09][SUCCESS] Sequelize: init successed
[2021-07-09 14:43:09][SUCCESS] ImageGenerator: init successed
(node:47874) UnhandledPromiseRejectionWarning: /home/ubuntu/gubot/src/service/cqhttp.js:4
    wsApi;
         ^

SyntaxError: Unexpected token ;
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Bot.initCqhttps (/home/ubuntu/gubot/src/service/bot.js:83:24)
    at /home/ubuntu/gubot/app.js:10:15
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:47874) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:47874) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
ubuntu@VM-8-13-ubuntu:~/gubot$ vim src/service/cqhttp.js
```

**Comment by x3zvawq** [comment]
看起来是由于您的nodejs版本过低导致的
第一个报错??运算符是一个类似||的运算符 用于取默认值
第二个报错是es6的class语法（可能有一些出入
建议更新一下nodejs的版本，服务器的nodejs版本为v15.14.0
关于如何在ubuntu更新ubuntu可以参考https://github.com/tj/n
