### ISSUE TITLE
帮助或者/help错误

### ISSUE THREAD

**Issue by chendongde310** [X3ZvaWQ/gubot#7]
TypeError: Cannot read property 'newPage' of undefined
    at Function.generateFromHtmlFile (/root/goubot/src/service/image.js:19:44)
    at Function.generateFromHtml (/root/goubot/src/service/image.js:59:33)
    at async Function.generateFromMarkdown (/root/goubot/src/service/image.js:96:16)
    at async Function.generateFromMarkdownFile (/root/goubot/src/service/image.js:86:16)
    at async HelpHandler.handle (/root/goubot/src/commands/help.js:11:21)
    at async Bot.handleCommand (/root/goubot/src/service/bot.js:25:24)
    at async Bot.handleMessage (/root/goubot/src/service/bot.js:122:24)
    at async WebSocket.<anonymous> (/root/goubot/src/main.js:121:26)

**Comment by x3zvawq** [comment]
这个问题是由于puppeteer未正常初始化导致的
你可能需要检查env.json内的配置确保enable_puppeteer配置项启动
